name: loom_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.0
  flutter_riverpod: ^2.4.0
  go_router: ^15.1.2
  shared_preferences: ^2.2.2
  logger: ^2.0.2
  intl: ^0.20.2
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  badges: ^3.1.1
  jwt_decoder: ^2.0.1
  mapbox_maps_flutter: ^2.8.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
